import { z } from "zod";

const emojiRequestSchema = z.string();
const timeZoneRequestSchema = z.string();

// -- Generated by ts-to-zod --
const idRequestSchema = z.union([z.string(), z.string()]);

const personUserObjectResponseSchema = z.object({
  type: z.literal("person"),
  person: z.object({
    email: z.string().optional(),
  }),
  name: z.string().nullable(),
  avatar_url: z.string().nullable(),
  id: idRequestSchema,
  object: z.literal("user"),
});

const emptyObjectSchema = z.record(z.never());

const partialUserObjectResponseSchema = z.object({
  id: idRequestSchema,
  object: z.literal("user"),
});

const botUserObjectResponseSchema = z.object({
  type: z.literal("bot"),
  bot: z.union([
    emptyObjectSchema,
    z.object({
      owner: z.union([
        z.object({
          type: z.literal("user"),
          user: z.union([
            z.object({
              type: z.literal("person"),
              person: z.object({
                email: z.string(),
              }),
              name: z.string().nullable(),
              avatar_url: z.string().nullable(),
              id: idRequestSchema,
              object: z.literal("user"),
            }),
            partialUserObjectResponseSchema,
          ]),
        }),
        z.object({
          type: z.literal("workspace"),
          workspace: z.literal(true),
        }),
      ]),
      workspace_name: z.string().nullable(),
    }),
  ]),
  name: z.string().nullable(),
  avatar_url: z.string().nullable(),
  id: idRequestSchema,
  object: z.literal("user"),
});

const userObjectResponseSchema = z.union([
  personUserObjectResponseSchema,
  botUserObjectResponseSchema,
]);

const selectColorSchema = z.union([
  z.literal("default"),
  z.literal("gray"),
  z.literal("brown"),
  z.literal("orange"),
  z.literal("yellow"),
  z.literal("green"),
  z.literal("blue"),
  z.literal("purple"),
  z.literal("pink"),
  z.literal("red"),
]);

const partialSelectResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  color: selectColorSchema,
});

const dateResponseSchema = z.object({
  start: z.string(),
  end: z.string().nullable(),
  time_zone: timeZoneRequestSchema.nullable(),
});

const stringRequestSchema = z.string();

const textRequestSchema = z.string();

const stringFormulaPropertyResponseSchema = z.object({
  type: z.literal("string"),
  string: z.string().nullable(),
});

const dateFormulaPropertyResponseSchema = z.object({
  type: z.literal("date"),
  date: dateResponseSchema.nullable(),
});

const numberFormulaPropertyResponseSchema = z.object({
  type: z.literal("number"),
  number: z.number().nullable(),
});

const booleanFormulaPropertyResponseSchema = z.object({
  type: z.literal("boolean"),
  boolean: z.boolean().nullable(),
});

const formulaPropertyResponseSchema = z.union([
  stringFormulaPropertyResponseSchema,
  dateFormulaPropertyResponseSchema,
  numberFormulaPropertyResponseSchema,
  booleanFormulaPropertyResponseSchema,
]);

const verificationPropertyUnverifiedResponseSchema = z.object({
  state: z.literal("unverified"),
  date: z.null(),
  verified_by: z.null(),
});

const verificationPropertyResponseSchema = z.object({
  state: z.union([z.literal("verified"), z.literal("expired")]),
  date: dateResponseSchema.nullable(),
  verified_by: z
    .union([
      z.object({
        id: idRequestSchema,
      }),
      z.object({
        person: z.object({
          email: z.string().optional(),
        }),
        id: idRequestSchema,
        type: z.literal("person").optional(),
        name: z.string().optional().nullable(),
        avatar_url: z.string().optional().nullable(),
        object: z.literal("user").optional(),
      }),
      z.object({
        bot: z.union([
          emptyObjectSchema,
          z.object({
            owner: z.union([
              z.object({
                type: z.literal("user"),
                user: z.union([
                  z.object({
                    type: z.literal("person"),
                    person: z.object({
                      email: z.string(),
                    }),
                    name: z.string().nullable(),
                    avatar_url: z.string().nullable(),
                    id: idRequestSchema,
                    object: z.literal("user"),
                  }),
                  partialUserObjectResponseSchema,
                ]),
              }),
              z.object({
                type: z.literal("workspace"),
                workspace: z.literal(true),
              }),
            ]),
            workspace_name: z.string().nullable(),
          }),
        ]),
        id: idRequestSchema,
        type: z.literal("bot").optional(),
        name: z.string().optional().nullable(),
        avatar_url: z.string().optional().nullable(),
        object: z.literal("user").optional(),
      }),
    ])
    .nullable(),
});

const annotationResponseSchema = z.object({
  bold: z.boolean(),
  italic: z.boolean(),
  strikethrough: z.boolean(),
  underline: z.boolean(),
  code: z.boolean(),
  color: z.union([
    z.literal("default"),
    z.literal("gray"),
    z.literal("brown"),
    z.literal("orange"),
    z.literal("yellow"),
    z.literal("green"),
    z.literal("blue"),
    z.literal("purple"),
    z.literal("pink"),
    z.literal("red"),
    z.literal("default_background"),
    z.literal("gray_background"),
    z.literal("brown_background"),
    z.literal("orange_background"),
    z.literal("yellow_background"),
    z.literal("green_background"),
    z.literal("blue_background"),
    z.literal("purple_background"),
    z.literal("pink_background"),
    z.literal("red_background"),
  ]),
});

const textRichTextItemResponseSchema = z.object({
  type: z.literal("text"),
  text: z.object({
    content: z.string(),
    link: z
      .object({
        url: textRequestSchema,
      })
      .nullable(),
  }),
  annotations: annotationResponseSchema,
  plain_text: z.string(),
  href: z.string().nullable(),
});

const linkPreviewMentionResponseSchema = z.object({
  url: textRequestSchema,
});

const linkMentionResponseSchema = z.object({
  href: z.string(),
});

const templateMentionDateTemplateMentionResponseSchema = z.object({
  type: z.literal("template_mention_date"),
  template_mention_date: z.union([z.literal("today"), z.literal("now")]),
});

const templateMentionUserTemplateMentionResponseSchema = z.object({
  type: z.literal("template_mention_user"),
  template_mention_user: z.literal("me"),
});

const templateMentionResponseSchema = z.union([
  templateMentionDateTemplateMentionResponseSchema,
  templateMentionUserTemplateMentionResponseSchema,
]);

const customEmojiResponseSchema = z.object({
  id: idRequestSchema,
  name: z.string(),
  url: z.string(),
});

const mentionRichTextItemResponseSchema = z.object({
  type: z.literal("mention"),
  mention: z.union([
    z.object({
      type: z.literal("user"),
      user: z.union([
        partialUserObjectResponseSchema,
        userObjectResponseSchema,
      ]),
    }),
    z.object({
      type: z.literal("date"),
      date: dateResponseSchema,
    }),
    z.object({
      type: z.literal("link_preview"),
      link_preview: linkPreviewMentionResponseSchema,
    }),
    z.object({
      type: z.literal("link_mention"),
      link_mention: linkMentionResponseSchema,
    }),
    z.object({
      type: z.literal("template_mention"),
      template_mention: templateMentionResponseSchema,
    }),
    z.object({
      type: z.literal("page"),
      page: z.object({
        id: idRequestSchema,
      }),
    }),
    z.object({
      type: z.literal("database"),
      database: z.object({
        id: idRequestSchema,
      }),
    }),
    z.object({
      type: z.literal("custom_emoji"),
      custom_emoji: customEmojiResponseSchema,
    }),
  ]),
  annotations: annotationResponseSchema,
  plain_text: z.string(),
  href: z.string().nullable(),
});

const equationRichTextItemResponseSchema = z.object({
  type: z.literal("equation"),
  equation: z.object({
    expression: textRequestSchema,
  }),
  annotations: annotationResponseSchema,
  plain_text: z.string(),
  href: z.string().nullable(),
});

const richTextItemResponseSchema = z.union([
  textRichTextItemResponseSchema,
  mentionRichTextItemResponseSchema,
  equationRichTextItemResponseSchema,
]);

const rollupFunctionSchema = z.union([
  z.literal("count"),
  z.literal("count_values"),
  z.literal("empty"),
  z.literal("not_empty"),
  z.literal("unique"),
  z.literal("show_unique"),
  z.literal("percent_empty"),
  z.literal("percent_not_empty"),
  z.literal("sum"),
  z.literal("average"),
  z.literal("median"),
  z.literal("min"),
  z.literal("max"),
  z.literal("range"),
  z.literal("earliest_date"),
  z.literal("latest_date"),
  z.literal("date_range"),
  z.literal("checked"),
  z.literal("unchecked"),
  z.literal("percent_checked"),
  z.literal("percent_unchecked"),
  z.literal("count_per_group"),
  z.literal("percent_per_group"),
  z.literal("show_original"),
]);

// Generated by ts-to-zod --
export const numberPropertyPageObjectResponseSchema = z.object({
  type: z.literal("number"),
  number: z.number().nullable(),
  id: z.string(),
});

export const urlPropertyPageObjectResponseSchema = z.object({
  type: z.literal("url"),
  url: z.string().nullable(),
  id: z.string(),
});

export const selectPropertyPageObjectResponseSchema = z.object({
  type: z.literal("select"),
  select: partialSelectResponseSchema.nullable(),
  id: z.string(),
});

export const multiSelectPropertyPageObjectResponseSchema = z.object({
  type: z.literal("multi_select"),
  multi_select: z.array(partialSelectResponseSchema),
  id: z.string(),
});

export const statusPropertyPageObjectResponseSchema = z.object({
  type: z.literal("status"),
  status: partialSelectResponseSchema.nullable(),
  id: z.string(),
});

export const datePropertyPageObjectResponseSchema = z.object({
  type: z.literal("date"),
  date: dateResponseSchema.nullable(),
  id: z.string(),
});

export const emailPropertyPageObjectResponseSchema = z.object({
  type: z.literal("email"),
  email: z.string().nullable(),
  id: z.string(),
});

export const phoneNumberPropertyPageObjectResponseSchema = z.object({
  type: z.literal("phone_number"),
  phone_number: z.string().nullable(),
  id: z.string(),
});

export const checkboxPropertyPageObjectResponseSchema = z.object({
  type: z.literal("checkbox"),
  checkbox: z.boolean(),
  id: z.string(),
});

export const filesPropertyPageObjectResponseSchema = z.object({
  type: z.literal("files"),
  files: z.array(
    z.union([
      z.object({
        file: z.object({
          url: z.string(),
          expiry_time: z.string(),
        }),
        name: stringRequestSchema,
        type: z.literal("file").optional(),
      }),
      z.object({
        external: z.object({
          url: textRequestSchema,
        }),
        name: stringRequestSchema,
        type: z.literal("external").optional(),
      }),
    ]),
  ),
  id: z.string(),
});

export const createdByPropertyPageObjectResponseSchema = z.object({
  type: z.literal("created_by"),
  created_by: z.union([
    partialUserObjectResponseSchema,
    userObjectResponseSchema,
  ]),
  id: z.string(),
});

export const createdTimePropertyPageObjectResponseSchema = z.object({
  type: z.literal("created_time"),
  created_time: z.string(),
  id: z.string(),
});

export const lastEditedByPropertyPageObjectResponseSchema = z.object({
  type: z.literal("last_edited_by"),
  last_edited_by: z.union([
    partialUserObjectResponseSchema,
    userObjectResponseSchema,
  ]),
  id: z.string(),
});

export const lastEditedTimePropertyPageObjectResponseSchema = z.object({
  type: z.literal("last_edited_time"),
  last_edited_time: z.string(),
  id: z.string(),
});

export const formulaPropertyPageObjectResponseSchema = z.object({
  type: z.literal("formula"),
  formula: formulaPropertyResponseSchema,
  id: z.string(),
});

export const buttonPropertyPageObjectResponseSchema = z.object({
  type: z.literal("button"),
  button: z.record(z.never()),
  id: z.string(),
});

export const uniqueIdPropertyPageObjectResponseSchema = z.object({
  type: z.literal("unique_id"),
  unique_id: z.object({
    prefix: z.string().nullable(),
    number: z.number().nullable(),
  }),
  id: z.string(),
});

export const verificationPropertyPageObjectResponseSchema = z.object({
  type: z.literal("verification"),
  verification: z
    .union([
      verificationPropertyUnverifiedResponseSchema,
      verificationPropertyResponseSchema,
    ])
    .nullable(),
  id: z.string(),
});

export const titlePropertyPageObjectResponseSchema = z.object({
  type: z.literal("title"),
  title: z.array(textRichTextItemResponseSchema),
  id: z.string(),
});

export const richTextPropertyPageObjectResponseSchema = z.object({
  type: z.literal("rich_text"),
  rich_text: z.array(textRichTextItemResponseSchema),
  id: z.string(),
});

export const peoplePropertyPageObjectResponseSchema = z.object({
  type: z.literal("people"),
  people: z.array(
    z.union([partialUserObjectResponseSchema, userObjectResponseSchema]),
  ),
  id: z.string(),
});

export const relationPropertyPageObjectResponseSchema = z.object({
  type: z.literal("relation"),
  relation: z.array(
    z.object({
      id: z.string(),
    }),
  ),
  id: z.string(),
});

export const rollupPropertyPageObjectResponseSchema = z.object({
  type: z.literal("rollup"),
  rollup: z.union([
    z.object({
      type: z.literal("number"),
      number: z.number().nullable(),
      function: rollupFunctionSchema,
    }),
    z.object({
      type: z.literal("date"),
      date: dateResponseSchema.nullable(),
      function: rollupFunctionSchema,
    }),
    z.object({
      type: z.literal("array"),
      array: z.array(
        z.union([
          z.object({
            type: z.literal("number"),
            number: z.number().nullable(),
          }),
          z.object({
            type: z.literal("url"),
            url: z.string().nullable(),
          }),
          z.object({
            type: z.literal("select"),
            select: partialSelectResponseSchema.nullable(),
          }),
          z.object({
            type: z.literal("multi_select"),
            multi_select: z.array(partialSelectResponseSchema),
          }),
          z.object({
            type: z.literal("status"),
            status: partialSelectResponseSchema.nullable(),
          }),
          z.object({
            type: z.literal("date"),
            date: dateResponseSchema.nullable(),
          }),
          z.object({
            type: z.literal("email"),
            email: z.string().nullable(),
          }),
          z.object({
            type: z.literal("phone_number"),
            phone_number: z.string().nullable(),
          }),
          z.object({
            type: z.literal("checkbox"),
            checkbox: z.boolean(),
          }),
          z.object({
            type: z.literal("files"),
            files: z.array(
              z.union([
                z.object({
                  file: z.object({
                    url: z.string(),
                    expiry_time: z.string(),
                  }),
                  name: stringRequestSchema,
                  type: z.literal("file").optional(),
                }),
                z.object({
                  external: z.object({
                    url: textRequestSchema,
                  }),
                  name: stringRequestSchema,
                  type: z.literal("external").optional(),
                }),
              ]),
            ),
          }),
          z.object({
            type: z.literal("created_by"),
            created_by: z.union([
              partialUserObjectResponseSchema,
              userObjectResponseSchema,
            ]),
          }),
          z.object({
            type: z.literal("created_time"),
            created_time: z.string(),
          }),
          z.object({
            type: z.literal("last_edited_by"),
            last_edited_by: z.union([
              partialUserObjectResponseSchema,
              userObjectResponseSchema,
            ]),
          }),
          z.object({
            type: z.literal("last_edited_time"),
            last_edited_time: z.string(),
          }),
          z.object({
            type: z.literal("formula"),
            formula: formulaPropertyResponseSchema,
          }),
          z.object({
            type: z.literal("button"),
            button: z.record(z.never()),
          }),
          z.object({
            type: z.literal("unique_id"),
            unique_id: z.object({
              prefix: z.string().nullable(),
              number: z.number().nullable(),
            }),
          }),
          z.object({
            type: z.literal("verification"),
            verification: z
              .union([
                verificationPropertyUnverifiedResponseSchema,
                verificationPropertyResponseSchema,
              ])
              .nullable(),
          }),
          z.object({
            type: z.literal("title"),
            title: z.array(richTextItemResponseSchema),
          }),
          z.object({
            type: z.literal("rich_text"),
            rich_text: z.array(richTextItemResponseSchema),
          }),
          z.object({
            type: z.literal("people"),
            people: z.array(
              z.union([
                partialUserObjectResponseSchema,
                userObjectResponseSchema,
              ]),
            ),
          }),
          z.object({
            type: z.literal("relation"),
            relation: z.array(
              z.object({
                id: z.string(),
              }),
            ),
          }),
        ]),
      ),
      function: rollupFunctionSchema,
    }),
  ]),
  id: z.string(),
});

export const propertyPageObjectResponseSchema = z.union([
  numberPropertyPageObjectResponseSchema,
  urlPropertyPageObjectResponseSchema,
  selectPropertyPageObjectResponseSchema,
  multiSelectPropertyPageObjectResponseSchema,
  statusPropertyPageObjectResponseSchema,
  datePropertyPageObjectResponseSchema,
  emailPropertyPageObjectResponseSchema,
  phoneNumberPropertyPageObjectResponseSchema,
  checkboxPropertyPageObjectResponseSchema,
  filesPropertyPageObjectResponseSchema,
  createdByPropertyPageObjectResponseSchema,
  createdTimePropertyPageObjectResponseSchema,
  lastEditedByPropertyPageObjectResponseSchema,
  lastEditedTimePropertyPageObjectResponseSchema,
  formulaPropertyPageObjectResponseSchema,
  buttonPropertyPageObjectResponseSchema,
  uniqueIdPropertyPageObjectResponseSchema,
  verificationPropertyPageObjectResponseSchema,
  titlePropertyPageObjectResponseSchema,
  richTextPropertyPageObjectResponseSchema,
  peoplePropertyPageObjectResponseSchema,
  relationPropertyPageObjectResponseSchema,
  rollupPropertyPageObjectResponseSchema,
]);

export const pageObjectResponseSchema = z.object({
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
    z.object({
      type: z.literal("data_source_id"),
      data_source_id: z.string(),
    }),
  ]),
  properties: z.record(propertyPageObjectResponseSchema),
  icon: z
    .union([
      z.object({
        type: z.literal("emoji"),
        emoji: emojiRequestSchema,
      }),
      z.object({
        type: z.literal("external"),
        external: z.object({
          url: textRequestSchema,
        }),
      }),
      z.object({
        type: z.literal("file"),
        file: z.object({
          url: z.string(),
          expiry_time: z.string(),
        }),
      }),
      z.object({
        type: z.literal("custom_emoji"),
        custom_emoji: customEmojiResponseSchema,
      }),
    ])
    .nullable(),
  cover: z
    .union([
      z.object({
        type: z.literal("external"),
        external: z.object({
          url: textRequestSchema,
        }),
      }),
      z.object({
        type: z.literal("file"),
        file: z.object({
          url: z.string(),
          expiry_time: z.string(),
        }),
      }),
    ])
    .nullable(),
  created_by: partialUserObjectResponseSchema,
  last_edited_by: partialUserObjectResponseSchema,
  object: z.literal("page"),
  id: z.string(),
  created_time: z.string(),
  last_edited_time: z.string(),
  archived: z.boolean(),
  in_trash: z.boolean(),
  url: z.string(),
  public_url: z.string().nullable(),
});

export type PropertyPageObjectResponseType = z.infer<
  typeof propertyPageObjectResponseSchema
>;
export type PageObjectResponseType = z.infer<typeof pageObjectResponseSchema>;

export const pageWithMarkdownSchema = pageObjectResponseSchema.extend({
  markdown: z.string(),
});
export type PageWithMarkdownType = z.infer<typeof pageWithMarkdownSchema>;
