import { z } from "zod";

const emojiRequestSchema = z.string();
const timeZoneRequestSchema = z.string();

// -- Generated by ts-to-zod --
const idRequestSchema = z.union([z.string(), z.string()]);

export const personUserObjectResponseSchema = z.object({
  type: z.literal("person"),
  person: z.object({
    email: z.string().optional(),
  }),
  name: z.string().nullable(),
  avatar_url: z.string().nullable(),
  id: idRequestSchema,
  object: z.literal("user"),
});

const emptyObjectSchema = z.record(z.never());

export const partialUserObjectResponseSchema = z.object({
  id: idRequestSchema,
  object: z.literal("user"),
});

export const botUserObjectResponseSchema = z.object({
  type: z.literal("bot"),
  bot: z.union([
    emptyObjectSchema,
    z.object({
      owner: z.union([
        z.object({
          type: z.literal("user"),
          user: z.union([
            z.object({
              type: z.literal("person"),
              person: z.object({
                email: z.string(),
              }),
              name: z.string().nullable(),
              avatar_url: z.string().nullable(),
              id: idRequestSchema,
              object: z.literal("user"),
            }),
            partialUserObjectResponseSchema,
          ]),
        }),
        z.object({
          type: z.literal("workspace"),
          workspace: z.literal(true),
        }),
      ]),
      workspace_name: z.string().nullable(),
    }),
  ]),
  name: z.string().nullable(),
  avatar_url: z.string().nullable(),
  id: idRequestSchema,
  object: z.literal("user"),
});

export const userObjectResponseSchema = z.union([
  personUserObjectResponseSchema,
  botUserObjectResponseSchema,
]);

const selectColorSchema = z.union([
  z.literal("default"),
  z.literal("gray"),
  z.literal("brown"),
  z.literal("orange"),
  z.literal("yellow"),
  z.literal("green"),
  z.literal("blue"),
  z.literal("purple"),
  z.literal("pink"),
  z.literal("red"),
]);

const partialSelectResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  color: selectColorSchema,
});

const dateResponseSchema = z.object({
  start: z.string(),
  end: z.string().nullable(),
  time_zone: timeZoneRequestSchema.nullable(),
});

const stringRequestSchema = z.string();

const textRequestSchema = z.string();

const stringFormulaPropertyResponseSchema = z.object({
  type: z.literal("string"),
  string: z.string().nullable(),
});

const dateFormulaPropertyResponseSchema = z.object({
  type: z.literal("date"),
  date: dateResponseSchema.nullable(),
});

const numberFormulaPropertyResponseSchema = z.object({
  type: z.literal("number"),
  number: z.number().nullable(),
});

const booleanFormulaPropertyResponseSchema = z.object({
  type: z.literal("boolean"),
  boolean: z.boolean().nullable(),
});

const formulaPropertyResponseSchema = z.union([
  stringFormulaPropertyResponseSchema,
  dateFormulaPropertyResponseSchema,
  numberFormulaPropertyResponseSchema,
  booleanFormulaPropertyResponseSchema,
]);

const verificationPropertyUnverifiedResponseSchema = z.object({
  state: z.literal("unverified"),
  date: z.null(),
  verified_by: z.null(),
});

const verificationPropertyResponseSchema = z.object({
  state: z.union([z.literal("verified"), z.literal("expired")]),
  date: dateResponseSchema.nullable(),
  verified_by: z
    .union([
      z.object({
        id: idRequestSchema,
      }),
      z.object({
        person: z.object({
          email: z.string().optional(),
        }),
        id: idRequestSchema,
        type: z.literal("person").optional(),
        name: z.string().optional().nullable(),
        avatar_url: z.string().optional().nullable(),
        object: z.literal("user").optional(),
      }),
      z.object({
        bot: z.union([
          emptyObjectSchema,
          z.object({
            owner: z.union([
              z.object({
                type: z.literal("user"),
                user: z.union([
                  z.object({
                    type: z.literal("person"),
                    person: z.object({
                      email: z.string(),
                    }),
                    name: z.string().nullable(),
                    avatar_url: z.string().nullable(),
                    id: idRequestSchema,
                    object: z.literal("user"),
                  }),
                  partialUserObjectResponseSchema,
                ]),
              }),
              z.object({
                type: z.literal("workspace"),
                workspace: z.literal(true),
              }),
            ]),
            workspace_name: z.string().nullable(),
          }),
        ]),
        id: idRequestSchema,
        type: z.literal("bot").optional(),
        name: z.string().optional().nullable(),
        avatar_url: z.string().optional().nullable(),
        object: z.literal("user").optional(),
      }),
    ])
    .nullable(),
});

const annotationResponseSchema = z.object({
  bold: z.boolean(),
  italic: z.boolean(),
  strikethrough: z.boolean(),
  underline: z.boolean(),
  code: z.boolean(),
  color: z.union([
    z.literal("default"),
    z.literal("gray"),
    z.literal("brown"),
    z.literal("orange"),
    z.literal("yellow"),
    z.literal("green"),
    z.literal("blue"),
    z.literal("purple"),
    z.literal("pink"),
    z.literal("red"),
    z.literal("default_background"),
    z.literal("gray_background"),
    z.literal("brown_background"),
    z.literal("orange_background"),
    z.literal("yellow_background"),
    z.literal("green_background"),
    z.literal("blue_background"),
    z.literal("purple_background"),
    z.literal("pink_background"),
    z.literal("red_background"),
  ]),
});

export const textRichTextItemResponseSchema = z.object({
  type: z.literal("text"),
  text: z.object({
    content: z.string(),
    link: z
      .object({
        url: textRequestSchema,
      })
      .nullable(),
  }),
  annotations: annotationResponseSchema,
  plain_text: z.string(),
  href: z.string().nullable(),
});

const linkPreviewMentionResponseSchema = z.object({
  url: textRequestSchema,
});

const linkMentionResponseSchema = z.object({
  href: z.string(),
});

const templateMentionDateTemplateMentionResponseSchema = z.object({
  type: z.literal("template_mention_date"),
  template_mention_date: z.union([z.literal("today"), z.literal("now")]),
});

const templateMentionUserTemplateMentionResponseSchema = z.object({
  type: z.literal("template_mention_user"),
  template_mention_user: z.literal("me"),
});

const templateMentionResponseSchema = z.union([
  templateMentionDateTemplateMentionResponseSchema,
  templateMentionUserTemplateMentionResponseSchema,
]);

const customEmojiResponseSchema = z.object({
  id: idRequestSchema,
  name: z.string(),
  url: z.string(),
});

export const mentionRichTextItemResponseSchema = z.object({
  type: z.literal("mention"),
  mention: z.union([
    z.object({
      type: z.literal("user"),
      user: z.union([
        partialUserObjectResponseSchema,
        userObjectResponseSchema,
      ]),
    }),
    z.object({
      type: z.literal("date"),
      date: dateResponseSchema,
    }),
    z.object({
      type: z.literal("link_preview"),
      link_preview: linkPreviewMentionResponseSchema,
    }),
    z.object({
      type: z.literal("link_mention"),
      link_mention: linkMentionResponseSchema,
    }),
    z.object({
      type: z.literal("template_mention"),
      template_mention: templateMentionResponseSchema,
    }),
    z.object({
      type: z.literal("page"),
      page: z.object({
        id: idRequestSchema,
      }),
    }),
    z.object({
      type: z.literal("database"),
      database: z.object({
        id: idRequestSchema,
      }),
    }),
    z.object({
      type: z.literal("custom_emoji"),
      custom_emoji: customEmojiResponseSchema,
    }),
  ]),
  annotations: annotationResponseSchema,
  plain_text: z.string(),
  href: z.string().nullable(),
});

export const equationRichTextItemResponseSchema = z.object({
  type: z.literal("equation"),
  equation: z.object({
    expression: textRequestSchema,
  }),
  annotations: annotationResponseSchema,
  plain_text: z.string(),
  href: z.string().nullable(),
});

export const richTextItemResponseSchema = z.union([
  textRichTextItemResponseSchema,
  mentionRichTextItemResponseSchema,
  equationRichTextItemResponseSchema,
]);

const rollupFunctionSchema = z.union([
  z.literal("count"),
  z.literal("count_values"),
  z.literal("empty"),
  z.literal("not_empty"),
  z.literal("unique"),
  z.literal("show_unique"),
  z.literal("percent_empty"),
  z.literal("percent_not_empty"),
  z.literal("sum"),
  z.literal("average"),
  z.literal("median"),
  z.literal("min"),
  z.literal("max"),
  z.literal("range"),
  z.literal("earliest_date"),
  z.literal("latest_date"),
  z.literal("date_range"),
  z.literal("checked"),
  z.literal("unchecked"),
  z.literal("percent_checked"),
  z.literal("percent_unchecked"),
  z.literal("count_per_group"),
  z.literal("percent_per_group"),
  z.literal("show_original"),
]);

const apiColorSchema = z.union([
  z.literal("default"),
  z.literal("gray"),
  z.literal("brown"),
  z.literal("orange"),
  z.literal("yellow"),
  z.literal("green"),
  z.literal("blue"),
  z.literal("purple"),
  z.literal("pink"),
  z.literal("red"),
  z.literal("default_background"),
  z.literal("gray_background"),
  z.literal("brown_background"),
  z.literal("orange_background"),
  z.literal("yellow_background"),
  z.literal("green_background"),
  z.literal("blue_background"),
  z.literal("purple_background"),
  z.literal("pink_background"),
  z.literal("red_background"),
]);

export const paragraphBlockObjectResponseSchema = z.object({
  type: z.literal("paragraph"),
  paragraph: z.object({
    rich_text: z.array(richTextItemResponseSchema),
    color: apiColorSchema,
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const heading1BlockObjectResponseSchema = z.object({
  type: z.literal("heading_1"),
  heading_1: z.object({
    rich_text: z.array(richTextItemResponseSchema),
    color: apiColorSchema,
    is_toggleable: z.boolean(),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const heading2BlockObjectResponseSchema = z.object({
  type: z.literal("heading_2"),
  heading_2: z.object({
    rich_text: z.array(richTextItemResponseSchema),
    color: apiColorSchema,
    is_toggleable: z.boolean(),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const heading3BlockObjectResponseSchema = z.object({
  type: z.literal("heading_3"),
  heading_3: z.object({
    rich_text: z.array(richTextItemResponseSchema),
    color: apiColorSchema,
    is_toggleable: z.boolean(),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const bulletedListItemBlockObjectResponseSchema = z.object({
  type: z.literal("bulleted_list_item"),
  bulleted_list_item: z.object({
    rich_text: z.array(richTextItemResponseSchema),
    color: apiColorSchema,
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const numberedListItemBlockObjectResponseSchema = z.object({
  type: z.literal("numbered_list_item"),
  numbered_list_item: z.object({
    rich_text: z.array(richTextItemResponseSchema),
    color: apiColorSchema,
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const quoteBlockObjectResponseSchema = z.object({
  type: z.literal("quote"),
  quote: z.object({
    rich_text: z.array(richTextItemResponseSchema),
    color: apiColorSchema,
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const toDoBlockObjectResponseSchema = z.object({
  type: z.literal("to_do"),
  to_do: z.object({
    rich_text: z.array(richTextItemResponseSchema),
    color: apiColorSchema,
    checked: z.boolean(),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const toggleBlockObjectResponseSchema = z.object({
  type: z.literal("toggle"),
  toggle: z.object({
    rich_text: z.array(richTextItemResponseSchema),
    color: apiColorSchema,
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const templateBlockObjectResponseSchema = z.object({
  type: z.literal("template"),
  template: z.object({
    rich_text: z.array(richTextItemResponseSchema),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const syncedBlockBlockObjectResponseSchema = z.object({
  type: z.literal("synced_block"),
  synced_block: z.object({
    synced_from: z
      .object({
        type: z.literal("block_id"),
        block_id: idRequestSchema,
      })
      .nullable(),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const childPageBlockObjectResponseSchema = z.object({
  type: z.literal("child_page"),
  child_page: z.object({
    title: z.string(),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const childDatabaseBlockObjectResponseSchema = z.object({
  type: z.literal("child_database"),
  child_database: z.object({
    title: z.string(),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const equationBlockObjectResponseSchema = z.object({
  type: z.literal("equation"),
  equation: z.object({
    expression: z.string(),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

const languageRequestSchema = z.union([
  z.literal("abap"),
  z.literal("agda"),
  z.literal("arduino"),
  z.literal("ascii art"),
  z.literal("assembly"),
  z.literal("bash"),
  z.literal("basic"),
  z.literal("bnf"),
  z.literal("c"),
  z.literal("c#"),
  z.literal("c++"),
  z.literal("clojure"),
  z.literal("coffeescript"),
  z.literal("coq"),
  z.literal("css"),
  z.literal("dart"),
  z.literal("dhall"),
  z.literal("diff"),
  z.literal("docker"),
  z.literal("ebnf"),
  z.literal("elixir"),
  z.literal("elm"),
  z.literal("erlang"),
  z.literal("f#"),
  z.literal("flow"),
  z.literal("fortran"),
  z.literal("gherkin"),
  z.literal("glsl"),
  z.literal("go"),
  z.literal("graphql"),
  z.literal("groovy"),
  z.literal("haskell"),
  z.literal("hcl"),
  z.literal("html"),
  z.literal("idris"),
  z.literal("java"),
  z.literal("javascript"),
  z.literal("json"),
  z.literal("julia"),
  z.literal("kotlin"),
  z.literal("latex"),
  z.literal("less"),
  z.literal("lisp"),
  z.literal("livescript"),
  z.literal("llvm ir"),
  z.literal("lua"),
  z.literal("makefile"),
  z.literal("markdown"),
  z.literal("markup"),
  z.literal("matlab"),
  z.literal("mathematica"),
  z.literal("mermaid"),
  z.literal("nix"),
  z.literal("notion formula"),
  z.literal("objective-c"),
  z.literal("ocaml"),
  z.literal("pascal"),
  z.literal("perl"),
  z.literal("php"),
  z.literal("plain text"),
  z.literal("powershell"),
  z.literal("prolog"),
  z.literal("protobuf"),
  z.literal("purescript"),
  z.literal("python"),
  z.literal("r"),
  z.literal("racket"),
  z.literal("reason"),
  z.literal("ruby"),
  z.literal("rust"),
  z.literal("sass"),
  z.literal("scala"),
  z.literal("scheme"),
  z.literal("scss"),
  z.literal("shell"),
  z.literal("smalltalk"),
  z.literal("solidity"),
  z.literal("sql"),
  z.literal("swift"),
  z.literal("toml"),
  z.literal("typescript"),
  z.literal("vb.net"),
  z.literal("verilog"),
  z.literal("vhdl"),
  z.literal("visual basic"),
  z.literal("webassembly"),
  z.literal("xml"),
  z.literal("yaml"),
  z.literal("java/c/c++/c#"),
]);

export const codeBlockObjectResponseSchema = z.object({
  type: z.literal("code"),
  code: z.object({
    rich_text: z.array(richTextItemResponseSchema),
    caption: z.array(richTextItemResponseSchema),
    language: languageRequestSchema,
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const calloutBlockObjectResponseSchema = z.object({
  type: z.literal("callout"),
  callout: z.object({
    rich_text: z.array(richTextItemResponseSchema),
    color: apiColorSchema,
    icon: z
      .union([
        z.object({
          type: z.literal("emoji"),
          emoji: emojiRequestSchema,
        }),
        z.object({
          type: z.literal("external"),
          external: z.object({
            url: textRequestSchema,
          }),
        }),
        z.object({
          type: z.literal("file"),
          file: z.object({
            url: z.string(),
            expiry_time: z.string(),
          }),
        }),
        z.object({
          type: z.literal("custom_emoji"),
          custom_emoji: customEmojiResponseSchema,
        }),
      ])
      .nullable(),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const dividerBlockObjectResponseSchema = z.object({
  type: z.literal("divider"),
  divider: emptyObjectSchema,
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const breadcrumbBlockObjectResponseSchema = z.object({
  type: z.literal("breadcrumb"),
  breadcrumb: emptyObjectSchema,
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const tableOfContentsBlockObjectResponseSchema = z.object({
  type: z.literal("table_of_contents"),
  table_of_contents: z.object({
    color: apiColorSchema,
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const columnListBlockObjectResponseSchema = z.object({
  type: z.literal("column_list"),
  column_list: emptyObjectSchema,
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const columnBlockObjectResponseSchema = z.object({
  type: z.literal("column"),
  column: emptyObjectSchema,
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const linkToPageBlockObjectResponseSchema = z.object({
  type: z.literal("link_to_page"),
  link_to_page: z.union([
    z.object({
      type: z.literal("page_id"),
      page_id: idRequestSchema,
    }),
    z.object({
      type: z.literal("database_id"),
      database_id: idRequestSchema,
    }),
    z.object({
      type: z.literal("comment_id"),
      comment_id: idRequestSchema,
    }),
  ]),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const tableBlockObjectResponseSchema = z.object({
  type: z.literal("table"),
  table: z.object({
    has_column_header: z.boolean(),
    has_row_header: z.boolean(),
    table_width: z.number(),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const tableRowBlockObjectResponseSchema = z.object({
  type: z.literal("table_row"),
  table_row: z.object({
    cells: z.array(z.array(richTextItemResponseSchema)),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const embedBlockObjectResponseSchema = z.object({
  type: z.literal("embed"),
  embed: z.object({
    url: z.string(),
    caption: z.array(richTextItemResponseSchema),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const bookmarkBlockObjectResponseSchema = z.object({
  type: z.literal("bookmark"),
  bookmark: z.object({
    url: z.string(),
    caption: z.array(richTextItemResponseSchema),
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const imageBlockObjectResponseSchema = z.object({
  type: z.literal("image"),
  image: z.union([
    z.object({
      type: z.literal("external"),
      external: z.object({
        url: textRequestSchema,
      }),
      caption: z.array(richTextItemResponseSchema),
    }),
    z.object({
      type: z.literal("file"),
      file: z.object({
        url: z.string(),
        expiry_time: z.string(),
      }),
      caption: z.array(richTextItemResponseSchema),
    }),
  ]),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const videoBlockObjectResponseSchema = z.object({
  type: z.literal("video"),
  video: z.union([
    z.object({
      type: z.literal("external"),
      external: z.object({
        url: textRequestSchema,
      }),
      caption: z.array(richTextItemResponseSchema),
    }),
    z.object({
      type: z.literal("file"),
      file: z.object({
        url: z.string(),
        expiry_time: z.string(),
      }),
      caption: z.array(richTextItemResponseSchema),
    }),
  ]),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const pdfBlockObjectResponseSchema = z.object({
  type: z.literal("pdf"),
  pdf: z.union([
    z.object({
      type: z.literal("external"),
      external: z.object({
        url: textRequestSchema,
      }),
      caption: z.array(richTextItemResponseSchema),
    }),
    z.object({
      type: z.literal("file"),
      file: z.object({
        url: z.string(),
        expiry_time: z.string(),
      }),
      caption: z.array(richTextItemResponseSchema),
    }),
  ]),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const fileBlockObjectResponseSchema = z.object({
  type: z.literal("file"),
  file: z.union([
    z.object({
      type: z.literal("external"),
      external: z.object({
        url: textRequestSchema,
      }),
      caption: z.array(richTextItemResponseSchema),
      name: z.string(),
    }),
    z.object({
      type: z.literal("file"),
      file: z.object({
        url: z.string(),
        expiry_time: z.string(),
      }),
      caption: z.array(richTextItemResponseSchema),
      name: z.string(),
    }),
  ]),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const audioBlockObjectResponseSchema = z.object({
  type: z.literal("audio"),
  audio: z.union([
    z.object({
      type: z.literal("external"),
      external: z.object({
        url: textRequestSchema,
      }),
      caption: z.array(richTextItemResponseSchema),
    }),
    z.object({
      type: z.literal("file"),
      file: z.object({
        url: z.string(),
        expiry_time: z.string(),
      }),
      caption: z.array(richTextItemResponseSchema),
    }),
  ]),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const linkPreviewBlockObjectResponseSchema = z.object({
  type: z.literal("link_preview"),
  link_preview: z.object({
    url: textRequestSchema,
  }),
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const unsupportedBlockObjectResponseSchema = z.object({
  type: z.literal("unsupported"),
  unsupported: emptyObjectSchema,
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  object: z.literal("block"),
  id: z.string(),
  created_time: z.string(),
  created_by: partialUserObjectResponseSchema,
  last_edited_time: z.string(),
  last_edited_by: partialUserObjectResponseSchema,
  has_children: z.boolean(),
  archived: z.boolean(),
  in_trash: z.boolean(),
});

export const blockObjectResponseSchema = z.union([
  paragraphBlockObjectResponseSchema,
  heading1BlockObjectResponseSchema,
  heading2BlockObjectResponseSchema,
  heading3BlockObjectResponseSchema,
  bulletedListItemBlockObjectResponseSchema,
  numberedListItemBlockObjectResponseSchema,
  quoteBlockObjectResponseSchema,
  toDoBlockObjectResponseSchema,
  toggleBlockObjectResponseSchema,
  templateBlockObjectResponseSchema,
  syncedBlockBlockObjectResponseSchema,
  childPageBlockObjectResponseSchema,
  childDatabaseBlockObjectResponseSchema,
  equationBlockObjectResponseSchema,
  codeBlockObjectResponseSchema,
  calloutBlockObjectResponseSchema,
  dividerBlockObjectResponseSchema,
  breadcrumbBlockObjectResponseSchema,
  tableOfContentsBlockObjectResponseSchema,
  columnListBlockObjectResponseSchema,
  columnBlockObjectResponseSchema,
  linkToPageBlockObjectResponseSchema,
  tableBlockObjectResponseSchema,
  tableRowBlockObjectResponseSchema,
  embedBlockObjectResponseSchema,
  bookmarkBlockObjectResponseSchema,
  imageBlockObjectResponseSchema,
  videoBlockObjectResponseSchema,
  pdfBlockObjectResponseSchema,
  fileBlockObjectResponseSchema,
  audioBlockObjectResponseSchema,
  linkPreviewBlockObjectResponseSchema,
  unsupportedBlockObjectResponseSchema,
]);
// Generated by ts-to-zod --
export const numberPropertyPageObjectResponseSchema = z.object({
  type: z.literal("number"),
  number: z.number().nullable(),
  id: z.string(),
});

export const urlPropertyPageObjectResponseSchema = z.object({
  type: z.literal("url"),
  url: z.string().nullable(),
  id: z.string(),
});

export const selectPropertyPageObjectResponseSchema = z.object({
  type: z.literal("select"),
  select: partialSelectResponseSchema.nullable(),
  id: z.string(),
});

export const multiSelectPropertyPageObjectResponseSchema = z.object({
  type: z.literal("multi_select"),
  multi_select: z.array(partialSelectResponseSchema),
  id: z.string(),
});

export const statusPropertyPageObjectResponseSchema = z.object({
  type: z.literal("status"),
  status: partialSelectResponseSchema.nullable(),
  id: z.string(),
});

export const datePropertyPageObjectResponseSchema = z.object({
  type: z.literal("date"),
  date: dateResponseSchema.nullable(),
  id: z.string(),
});

export const emailPropertyPageObjectResponseSchema = z.object({
  type: z.literal("email"),
  email: z.string().nullable(),
  id: z.string(),
});

export const phoneNumberPropertyPageObjectResponseSchema = z.object({
  type: z.literal("phone_number"),
  phone_number: z.string().nullable(),
  id: z.string(),
});

export const checkboxPropertyPageObjectResponseSchema = z.object({
  type: z.literal("checkbox"),
  checkbox: z.boolean(),
  id: z.string(),
});

export const filesPropertyPageObjectResponseSchema = z.object({
  type: z.literal("files"),
  files: z.array(
    z.union([
      z.object({
        file: z.object({
          url: z.string(),
          expiry_time: z.string(),
        }),
        name: stringRequestSchema,
        type: z.literal("file").optional(),
      }),
      z.object({
        external: z.object({
          url: textRequestSchema,
        }),
        name: stringRequestSchema,
        type: z.literal("external").optional(),
      }),
    ]),
  ),
  id: z.string(),
});

export const createdByPropertyPageObjectResponseSchema = z.object({
  type: z.literal("created_by"),
  created_by: z.union([
    partialUserObjectResponseSchema,
    userObjectResponseSchema,
  ]),
  id: z.string(),
});

export const createdTimePropertyPageObjectResponseSchema = z.object({
  type: z.literal("created_time"),
  created_time: z.string(),
  id: z.string(),
});

export const lastEditedByPropertyPageObjectResponseSchema = z.object({
  type: z.literal("last_edited_by"),
  last_edited_by: z.union([
    partialUserObjectResponseSchema,
    userObjectResponseSchema,
  ]),
  id: z.string(),
});

export const lastEditedTimePropertyPageObjectResponseSchema = z.object({
  type: z.literal("last_edited_time"),
  last_edited_time: z.string(),
  id: z.string(),
});

export const formulaPropertyPageObjectResponseSchema = z.object({
  type: z.literal("formula"),
  formula: formulaPropertyResponseSchema,
  id: z.string(),
});

export const buttonPropertyPageObjectResponseSchema = z.object({
  type: z.literal("button"),
  button: z.record(z.never()),
  id: z.string(),
});

export const uniqueIdPropertyPageObjectResponseSchema = z.object({
  type: z.literal("unique_id"),
  unique_id: z.object({
    prefix: z.string().nullable(),
    number: z.number().nullable(),
  }),
  id: z.string(),
});

export const verificationPropertyPageObjectResponseSchema = z.object({
  type: z.literal("verification"),
  verification: z
    .union([
      verificationPropertyUnverifiedResponseSchema,
      verificationPropertyResponseSchema,
    ])
    .nullable(),
  id: z.string(),
});

export const titlePropertyPageObjectResponseSchema = z.object({
  type: z.literal("title"),
  title: z.array(textRichTextItemResponseSchema),
  id: z.string(),
});

export const richTextPropertyPageObjectResponseSchema = z.object({
  type: z.literal("rich_text"),
  rich_text: z.array(textRichTextItemResponseSchema),
  id: z.string(),
});

export const peoplePropertyPageObjectResponseSchema = z.object({
  type: z.literal("people"),
  people: z.array(
    z.union([partialUserObjectResponseSchema, userObjectResponseSchema]),
  ),
  id: z.string(),
});

export const relationPropertyPageObjectResponseSchema = z.object({
  type: z.literal("relation"),
  relation: z.array(
    z.object({
      id: z.string(),
    }),
  ),
  id: z.string(),
});

export const rollupPropertyPageObjectResponseSchema = z.object({
  type: z.literal("rollup"),
  rollup: z.union([
    z.object({
      type: z.literal("number"),
      number: z.number().nullable(),
      function: rollupFunctionSchema,
    }),
    z.object({
      type: z.literal("date"),
      date: dateResponseSchema.nullable(),
      function: rollupFunctionSchema,
    }),
    z.object({
      type: z.literal("array"),
      array: z.array(
        z.union([
          z.object({
            type: z.literal("number"),
            number: z.number().nullable(),
          }),
          z.object({
            type: z.literal("url"),
            url: z.string().nullable(),
          }),
          z.object({
            type: z.literal("select"),
            select: partialSelectResponseSchema.nullable(),
          }),
          z.object({
            type: z.literal("multi_select"),
            multi_select: z.array(partialSelectResponseSchema),
          }),
          z.object({
            type: z.literal("status"),
            status: partialSelectResponseSchema.nullable(),
          }),
          z.object({
            type: z.literal("date"),
            date: dateResponseSchema.nullable(),
          }),
          z.object({
            type: z.literal("email"),
            email: z.string().nullable(),
          }),
          z.object({
            type: z.literal("phone_number"),
            phone_number: z.string().nullable(),
          }),
          z.object({
            type: z.literal("checkbox"),
            checkbox: z.boolean(),
          }),
          z.object({
            type: z.literal("files"),
            files: z.array(
              z.union([
                z.object({
                  file: z.object({
                    url: z.string(),
                    expiry_time: z.string(),
                  }),
                  name: stringRequestSchema,
                  type: z.literal("file").optional(),
                }),
                z.object({
                  external: z.object({
                    url: textRequestSchema,
                  }),
                  name: stringRequestSchema,
                  type: z.literal("external").optional(),
                }),
              ]),
            ),
          }),
          z.object({
            type: z.literal("created_by"),
            created_by: z.union([
              partialUserObjectResponseSchema,
              userObjectResponseSchema,
            ]),
          }),
          z.object({
            type: z.literal("created_time"),
            created_time: z.string(),
          }),
          z.object({
            type: z.literal("last_edited_by"),
            last_edited_by: z.union([
              partialUserObjectResponseSchema,
              userObjectResponseSchema,
            ]),
          }),
          z.object({
            type: z.literal("last_edited_time"),
            last_edited_time: z.string(),
          }),
          z.object({
            type: z.literal("formula"),
            formula: formulaPropertyResponseSchema,
          }),
          z.object({
            type: z.literal("button"),
            button: z.record(z.never()),
          }),
          z.object({
            type: z.literal("unique_id"),
            unique_id: z.object({
              prefix: z.string().nullable(),
              number: z.number().nullable(),
            }),
          }),
          z.object({
            type: z.literal("verification"),
            verification: z
              .union([
                verificationPropertyUnverifiedResponseSchema,
                verificationPropertyResponseSchema,
              ])
              .nullable(),
          }),
          z.object({
            type: z.literal("title"),
            title: z.array(richTextItemResponseSchema),
          }),
          z.object({
            type: z.literal("rich_text"),
            rich_text: z.array(richTextItemResponseSchema),
          }),
          z.object({
            type: z.literal("people"),
            people: z.array(
              z.union([
                partialUserObjectResponseSchema,
                userObjectResponseSchema,
              ]),
            ),
          }),
          z.object({
            type: z.literal("relation"),
            relation: z.array(
              z.object({
                id: z.string(),
              }),
            ),
          }),
        ]),
      ),
      function: rollupFunctionSchema,
    }),
  ]),
  id: z.string(),
});

export const propertyPageObjectResponseSchema = z.union([
  numberPropertyPageObjectResponseSchema,
  urlPropertyPageObjectResponseSchema,
  selectPropertyPageObjectResponseSchema,
  multiSelectPropertyPageObjectResponseSchema,
  statusPropertyPageObjectResponseSchema,
  datePropertyPageObjectResponseSchema,
  emailPropertyPageObjectResponseSchema,
  phoneNumberPropertyPageObjectResponseSchema,
  checkboxPropertyPageObjectResponseSchema,
  filesPropertyPageObjectResponseSchema,
  createdByPropertyPageObjectResponseSchema,
  createdTimePropertyPageObjectResponseSchema,
  lastEditedByPropertyPageObjectResponseSchema,
  lastEditedTimePropertyPageObjectResponseSchema,
  formulaPropertyPageObjectResponseSchema,
  buttonPropertyPageObjectResponseSchema,
  uniqueIdPropertyPageObjectResponseSchema,
  verificationPropertyPageObjectResponseSchema,
  titlePropertyPageObjectResponseSchema,
  richTextPropertyPageObjectResponseSchema,
  peoplePropertyPageObjectResponseSchema,
  relationPropertyPageObjectResponseSchema,
  rollupPropertyPageObjectResponseSchema,
]);

export const pageObjectResponseSchema = z.object({
  parent: z.union([
    z.object({
      type: z.literal("database_id"),
      database_id: z.string(),
    }),
    z.object({
      type: z.literal("page_id"),
      page_id: z.string(),
    }),
    z.object({
      type: z.literal("block_id"),
      block_id: z.string(),
    }),
    z.object({
      type: z.literal("workspace"),
      workspace: z.literal(true),
    }),
  ]),
  properties: z.record(propertyPageObjectResponseSchema),
  icon: z
    .union([
      z.object({
        type: z.literal("emoji"),
        emoji: emojiRequestSchema,
      }),
      z.object({
        type: z.literal("external"),
        external: z.object({
          url: textRequestSchema,
        }),
      }),
      z.object({
        type: z.literal("file"),
        file: z.object({
          url: z.string(),
          expiry_time: z.string(),
        }),
      }),
      z.object({
        type: z.literal("custom_emoji"),
        custom_emoji: customEmojiResponseSchema,
      }),
    ])
    .nullable(),
  cover: z
    .union([
      z.object({
        type: z.literal("external"),
        external: z.object({
          url: textRequestSchema,
        }),
      }),
      z.object({
        type: z.literal("file"),
        file: z.object({
          url: z.string(),
          expiry_time: z.string(),
        }),
      }),
    ])
    .nullable(),
  created_by: partialUserObjectResponseSchema,
  last_edited_by: partialUserObjectResponseSchema,
  object: z.literal("page"),
  id: z.string(),
  created_time: z.string(),
  last_edited_time: z.string(),
  archived: z.boolean(),
  in_trash: z.boolean(),
  url: z.string(),
  public_url: z.string().nullable(),
});

export type RichTextItemResponseType = z.infer<
  typeof richTextItemResponseSchema
>;

export type PropertyPageObjectResponseType = z.infer<
  typeof propertyPageObjectResponseSchema
>;
export type PageObjectResponseType = z.infer<typeof pageObjectResponseSchema>;

export type ParagraphBlockObjectResponseType = z.infer<
  typeof paragraphBlockObjectResponseSchema
>;
export type Heading1BlockObjectResponseType = z.infer<
  typeof heading1BlockObjectResponseSchema
>;
export type Heading2BlockObjectResponseType = z.infer<
  typeof heading2BlockObjectResponseSchema
>;
export type Heading3BlockObjectResponseType = z.infer<
  typeof heading3BlockObjectResponseSchema
>;
export type BulletedListItemBlockObjectResponseType = z.infer<
  typeof bulletedListItemBlockObjectResponseSchema
>;
export type NumberedListItemBlockObjectResponseType = z.infer<
  typeof numberedListItemBlockObjectResponseSchema
>;
export type QuoteBlockObjectResponseType = z.infer<
  typeof quoteBlockObjectResponseSchema
>;
export type ToDoBlockObjectResponseType = z.infer<
  typeof toDoBlockObjectResponseSchema
>;
export type ToggleBlockObjectResponseType = z.infer<
  typeof toggleBlockObjectResponseSchema
>;
export type TemplateBlockObjectResponseType = z.infer<
  typeof templateBlockObjectResponseSchema
>;
export type SyncedBlockBlockObjectResponseType = z.infer<
  typeof syncedBlockBlockObjectResponseSchema
>;
export type ChildPageBlockObjectResponseType = z.infer<
  typeof childPageBlockObjectResponseSchema
>;
export type ChildDatabaseBlockObjectResponseType = z.infer<
  typeof childDatabaseBlockObjectResponseSchema
>;
export type EquationBlockObjectResponseType = z.infer<
  typeof equationBlockObjectResponseSchema
>;
export type CodeBlockObjectResponseType = z.infer<
  typeof codeBlockObjectResponseSchema
>;
export type CalloutBlockObjectResponseType = z.infer<
  typeof calloutBlockObjectResponseSchema
>;
export type DividerBlockObjectResponseType = z.infer<
  typeof dividerBlockObjectResponseSchema
>;
export type BreadcrumbBlockObjectResponseType = z.infer<
  typeof breadcrumbBlockObjectResponseSchema
>;
export type TableOfContentsBlockObjectResponseType = z.infer<
  typeof tableOfContentsBlockObjectResponseSchema
>;
export type ColumnListBlockObjectResponseType = z.infer<
  typeof columnListBlockObjectResponseSchema
>;
export type ColumnBlockObjectResponseType = z.infer<
  typeof columnBlockObjectResponseSchema
>;
export type LinkToPageBlockObjectResponseType = z.infer<
  typeof linkToPageBlockObjectResponseSchema
>;
export type TableBlockObjectResponseType = z.infer<
  typeof tableBlockObjectResponseSchema
>;
export type TableRowBlockObjectResponseType = z.infer<
  typeof tableRowBlockObjectResponseSchema
>;
export type EmbedBlockObjectResponseType = z.infer<
  typeof embedBlockObjectResponseSchema
>;
export type BookmarkBlockObjectResponseType = z.infer<
  typeof bookmarkBlockObjectResponseSchema
>;
export type ImageBlockObjectResponseType = z.infer<
  typeof imageBlockObjectResponseSchema
>;
export type VideoBlockObjectResponseType = z.infer<
  typeof videoBlockObjectResponseSchema
>;
export type PdfBlockObjectResponseType = z.infer<
  typeof pdfBlockObjectResponseSchema
>;
export type FileBlockObjectResponseType = z.infer<
  typeof fileBlockObjectResponseSchema
>;
export type AudioBlockObjectResponseType = z.infer<
  typeof audioBlockObjectResponseSchema
>;
export type LinkPreviewBlockObjectResponseType = z.infer<
  typeof linkPreviewBlockObjectResponseSchema
>;
export type UnsupportedBlockObjectResponseType = z.infer<
  typeof unsupportedBlockObjectResponseSchema
>;
export type BlockObjectResponseType = z.infer<typeof blockObjectResponseSchema>;

export const blockObjectResponseWithChildrenSchema: z.ZodType = z.lazy(() =>
    blockObjectResponseSchema.and(
        z.object({
          children: z.array(blockObjectResponseWithChildrenSchema).optional(),
        })
    )
);

export const pageObjectResponseWithBlocksSchema =
    pageObjectResponseSchema.extend({
      blocks: z.array(blockObjectResponseWithChildrenSchema),
    });

export type BlockObjectResponseWithChildrenType = z.infer<typeof blockObjectResponseWithChildrenSchema>
export type PageObjectResponseWithBlocksType = z.infer<typeof pageObjectResponseWithBlocksSchema>
